### PR TITLE
property test plan

### PR DESCRIPTION
**Pull request by A60AB5450353F40E**

### CODE REVIEW

**Comment by emergent-reasons** [comment]
Going to leave enumerated main points from review:

1.
IMO, each test needs some explanation of *why*. The current pattern is:

- test X
- scripts

leaving it to the reader to decipher what each script is doing and why it's a meaningful test.

For example Fail: {undersized stack} {opcode} OP_DEPTH OP_{depthOut} OP_NUMEQUALVERIFY {OP_DROP x depthOut} OP_1

I can understand that this will fail in the first case. But then the next case where it succeeds... Why is this script meaningful? What does the logic accomplish? It's probably dead obvious to you, but my first reaction is ❔.

**Comment by emergent-reasons** [comment]
2.
My overall opinion as stated in #6 is that this doesn't really belong in the bigint CHIP, but rather a spec. Assuming this gets included though, the current state of this test plan is a VM op code test harness that happens to use numbers instead of a bigint test harness.

IMO, if you want to include it for confirming bigint, the steps should be isolated and simple:

`{a b c} OP_DEPTH` -> the item on top of the stack should be exactly `0x03` (or whatever the correctly formatted result is).

Side note - Using the VM to further validate the results creates an arguably circular assumption of validity, although I get why you want to do the validation with the VM itself. Not that fussed about using the VM to validate either if you want to.

Also to note - As I've said elsewhere I think it's fantastic to have this, it just feels out of place in the current form for this CHIP. If you really want to keep it, then perhaps it can be framed as what I described above - taking advantage of the bigint chip to create a new test-based specification for the VM op codes, and along the way it happens to check bigints.

**Comment by emergent-reasons** [comment]
3.

> When failing, the above test scripts must fail with ScriptError::INVALID_STACK_OPERATION error

Why does a general spec have implementation and even language-specific errors? Isn't it enough to say the script should fail? Alternatively, I guess you could state in the introduction that this is oriented around BCHN and then note inside when any details are specific to BCHN and need to be substituted for the implementation.

**Comment by A60AB5450353F40E** [comment]
re 1., stack test is kinda special, so explanation is in order:

We designed the stack depth test to fail on invalid stack state, but we have a "pass" test just to verify the test itself is good and will pass for a valid state.
This way we know that if there's some bug in the tested opcode where it could transform invalid stack state to valid, the test has a chance of actually passing for where it is expected to fail.

**Comment by A60AB5450353F40E** [comment]
re other points, I'll move the property-test-plan.md under BCHN since it's really coupled together, and we can just reference it from the CHIP tests section

**Pull request merged**
