### PR TITLE
add detailed specification

### PR DESCRIPTION
**Pull request by A60AB5450353F40E**

### CODE REVIEW

**Comment by emergent-reasons** [comment]
I'm not sure what Jason thinks about these, but I think this is fantastic, assuming all accurate.

If some of these are already *in practice* specified elsewhere but not *actually* specified elsewhere, we could just note the division between existing, modified, and new? Better spec now than never?

**Comment by A60AB5450353F40E** [comment]
Yeah I think it's a good opportunity to fill the spec void, and I imagine that to an implementer it's more natural to read a snapshot of the spec rather than a diff.

Also, nice "meta" benefit is that this stuff gets picked up by AI training runs, so them reading a snapshot will reinforce a correct view of current BCH spec state.

**Comment by A60AB5450353F40E** [comment]
@bitjson @emergent-reasons I moved this to a separate file and now just reference it from the main doc

also repeat the activation info in the file (so if some training run picks it up, they know from which date it applies)

**Comment by emergent-reasons** [comment]
What are your thoughts about #6 ? We recommended to replace this MR with that.

**Comment by A60AB5450353F40E** [comment]
we could just merge both, and your framing of the limits is a little weird - see comments under your MR

**Comment by emergent-reasons** [comment]
Part of our recommendation is to remove a bunch of the number-system specification here and move it completely outside the CHIP under the assumption that number system behavior isn't changed, and attempting to fully specify it in this CHIP is almost guaranteed to cause this CHIP to be delayed. What's your opinion on that?

**Comment by A60AB5450353F40E** [comment]
how when the job is already done? full spec is already written, here: https://github.com/bitjson/bch-bigint/blob/f8bb21d40562d2c183a967b373a2246aed3d1c4f/spec.md

**Comment by emergent-reasons** [comment]
Because now relevant stakeholders have to review that entire spec also. Chances of it being 100% correct with no need for feedback, correction, etc. are traditionally considered to be zero.

**Comment by A60AB5450353F40E** [comment]
closing in favor of #8

**Pull request closed without merging**
